#!/usr/bin/env python3
"""Export the production Postgres database to a D1-ready SQL file.

Run it locally (never in the Worker):

    cd api
    uv run --with 'psycopg[binary]' migrate/export_postgres.py \
        --database-url "$DATABASE_URL" --out migrate/data.sql

Then load it:

    npx wrangler d1 execute rachamais --remote --file migrate/data.sql

The three conversions that matter:

  * Decimal(10,2) -> integer cents. Done with Python's Decimal and an explicit
    ROUND_HALF_UP quantize, so 0.005 boundaries land where a human expects and
    no float ever touches the money.
  * timestamptz -> ISO-8601 UTC with milliseconds and a trailing Z, the exact
    format the old JSON API emitted and the app parses.
  * jsonb -> a JSON text column.

Passwords are copied across untouched: they are bcrypt hashes, which the Python
Worker cannot verify on its own. The LEGACY_BCRYPT service worker checks them at
login and the API rewrites each one as PBKDF2 on first successful sign-in.
"""

import argparse
import sys
from datetime import timezone
from decimal import ROUND_HALF_UP, Decimal

try:
    import psycopg
except ImportError:
    sys.exit("psycopg missing — run with: uv run --with 'psycopg[binary]' migrate/export_postgres.py ...")

# Insertion order satisfies the foreign keys.
TABLES = [
    ("users", ["id", "name", "email", "password", "avatarUrl", "pixKey", "createdAt", "updatedAt"]),
    ("groups", ["id", "name", "emoji", "description", "inviteCode", "createdById", "createdAt", "updatedAt"]),
    ("group_members", ["id", "groupId", "userId", "role", "joinedAt"]),
    ("expenses", ["id", "groupId", "paidById", "amount", "description", "category", "splitType", "date", "createdAt", "updatedAt"]),
    ("expense_splits", ["id", "expenseId", "userId", "amount", "percentage"]),
    ("settlements", ["id", "groupId", "fromUserId", "toUserId", "amount", "paymentMethod", "note", "settledAt", "createdAt"]),
    ("activities", ["id", "groupId", "userId", "type", "description", "metadata", "createdAt"]),
    ("device_tokens", ["id", "userId", "token", "platform", "createdAt", "updatedAt"]),
]

# Columns holding money — these become integer cents in D1.
MONEY_COLUMNS = {
    ("expenses", "amount"),
    ("expense_splits", "amount"),
    ("settlements", "amount"),
}

CHUNK = 200  # rows per INSERT statement


def to_cents(value) -> int:
    return int(
        (Decimal(value) * 100).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
    )


def iso(value) -> str:
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return (
        value.astimezone(timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def literal(value, table: str, column: str) -> str:
    if value is None:
        return "NULL"
    if (table, column) in MONEY_COLUMNS:
        return str(to_cents(value))
    if hasattr(value, "isoformat"):
        return "'" + iso(value) + "'"
    if isinstance(value, Decimal):  # expense_splits.percentage
        return str(float(value))
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dict, list)):  # activities.metadata (jsonb)
        import json

        return "'" + json.dumps(value, ensure_ascii=False).replace("'", "''") + "'"
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database-url", required=True)
    parser.add_argument("--out", default="migrate/data.sql")
    args = parser.parse_args()

    lines = [
        "-- Generated by migrate/export_postgres.py. Money is in integer cents.",
        "PRAGMA foreign_keys = OFF;",
        "BEGIN TRANSACTION;",
    ]
    totals = {}

    with psycopg.connect(args.database_url) as conn:
        for table, columns in TABLES:
            quoted = ", ".join(f'"{c}"' for c in columns)
            with conn.cursor() as cursor:
                cursor.execute(f"SELECT {quoted} FROM {table}")
                rows = cursor.fetchall()

            totals[table] = len(rows)
            if not rows:
                continue

            target_columns = ", ".join(f'"{c}"' for c in columns)
            for start in range(0, len(rows), CHUNK):
                chunk = rows[start : start + CHUNK]
                values = ",\n  ".join(
                    "("
                    + ", ".join(
                        literal(value, table, columns[i]) for i, value in enumerate(row)
                    )
                    + ")"
                    for row in chunk
                )
                lines.append(f"INSERT INTO {table} ({target_columns}) VALUES\n  {values};")

    lines += ["COMMIT;", "PRAGMA foreign_keys = ON;", ""]

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print(f"wrote {args.out}")
    for table, count in totals.items():
        print(f"  {table:16} {count:>7} rows")
    print("\nNow run:")
    print("  npx wrangler d1 execute rachamais --remote --file migrate/data.sql")


if __name__ == "__main__":
    main()
